language: generic

services:
  - docker

script:
  - docker build -t emoji-mart-vue:latest .
  - docker run emoji-mart-vue:latest npm run prettier-check
  - docker run emoji-mart-vue:latest bash -c "npm run jest && codecov"
